create database studio;
USE STUDIO;


CREATE TABLE AGENDAMENTOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CPF  VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA DATE NOT NULL,
    HORA TIME NOT NULL,
    VALOR float not NULL,
    PROCEDIMENTO VARCHAR(255) NOT NULL,
    TP_PAGAMENTO VARCHAR (255) NOT NULL 
);



SELECT 
    ID, 
    CPF, 
    NOME, 
    DATE_FORMAT(DATA, '%d/%m/%Y') AS DATA, 
    HORA, 
    PROCEDIMENTO, 
    TP_PAGAMENTO 
FROM AGENDAMENTOS
WHERE DATA = '2024-09-30';

select * from agendamentos;